### ISSUE TITLE
Code releasing?

### ISSUE THREAD

**Issue by Luoxd1996** [siyueyu/SCWSSOD#1]
Hi, Siyue,
Perfect work, and what's your timeline to release this code.
Best wishes;
Xiangde.

**Comment by siyueyu** [comment]
Hi, Xiangde @Luoxd1996 ,
Thanks for your following.
I will release the code around the conference time.
Kind regards,
Siyue

**Comment by Luoxd1996** [comment]
> Hi, Xiangde @Luoxd1996 ,
> Thanks for your following.
> I will release the code around the conference time.
> Kind regards,
> Siyue

Ok, thanks for your reply. I will wait for the code release.
Best,
Xiangde.
