### ISSUE TITLE
All foreground/background prediction

### ISSUE THREAD

**Issue by XuYunqiu** [siyueyu/SCWSSOD#3]
Thanks for sharing your code. The performance of your method is very promising. 
I try to train the model several times. I find the training seems not stable. Sometimes I get the reasonable saliency prediction maps. But sometimes the saliency maps are predicted as nearly all foreground or all background. 
Could you give me any suggestion. Is this problem also happen in your experiments?

The saliency prediction map generated by a collapsed model is like this:
![11](https://user-images.githubusercontent.com/23272227/109655125-e232e400-7b9d-11eb-9eed-5af426a6d100.png)

**Comment by siyueyu** [comment]
@XuYunqiu  I haven't met any like this outputs. Could you please share more information?

**Comment by XuYunqiu** [comment]
I think this issue happens when I train the model using a shared GPU (someone else also runs a job on this GPU). But I don't find out the detailed reason. When I use a free GPU, the outputs are good.
